# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/chris/anaconda3/lib/python3.12/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/chris/anaconda3/lib/python3.12/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chris/Desktop/TASEP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chris/Desktop/TASEP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/chris/anaconda3/lib/python3.12/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/chris/anaconda3/lib/python3.12/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/chris/anaconda3/lib/python3.12/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/chris/anaconda3/lib/python3.12/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/chris/anaconda3/lib/python3.12/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/chris/anaconda3/lib/python3.12/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/chris/anaconda3/lib/python3.12/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/chris/anaconda3/lib/python3.12/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/Desktop/TASEP/CMakeFiles /home/chris/Desktop/TASEP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/Desktop/TASEP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tasep

# Build rule for target.
tasep: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasep
.PHONY : tasep

# fast build rule for target.
tasep/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/build
.PHONY : tasep/fast

#=============================================================================
# Target rules for targets named neighbors

# Build rule for target.
neighbors: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neighbors
.PHONY : neighbors

# fast build rule for target.
neighbors/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighbors.dir/build.make CMakeFiles/neighbors.dir/build
.PHONY : neighbors/fast

#=============================================================================
# Target rules for targets named tasep_profile

# Build rule for target.
tasep_profile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasep_profile
.PHONY : tasep_profile

# fast build rule for target.
tasep_profile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep_profile.dir/build.make CMakeFiles/tasep_profile.dir/build
.PHONY : tasep_profile/fast

python/neighbors.o: python/neighbors.cpp.o
.PHONY : python/neighbors.o

# target to build an object file
python/neighbors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighbors.dir/build.make CMakeFiles/neighbors.dir/python/neighbors.cpp.o
.PHONY : python/neighbors.cpp.o

python/neighbors.i: python/neighbors.cpp.i
.PHONY : python/neighbors.i

# target to preprocess a source file
python/neighbors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighbors.dir/build.make CMakeFiles/neighbors.dir/python/neighbors.cpp.i
.PHONY : python/neighbors.cpp.i

python/neighbors.s: python/neighbors.cpp.s
.PHONY : python/neighbors.s

# target to generate assembly for a file
python/neighbors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighbors.dir/build.make CMakeFiles/neighbors.dir/python/neighbors.cpp.s
.PHONY : python/neighbors.cpp.s

python/profile.o: python/profile.cpp.o
.PHONY : python/profile.o

# target to build an object file
python/profile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep_profile.dir/build.make CMakeFiles/tasep_profile.dir/python/profile.cpp.o
.PHONY : python/profile.cpp.o

python/profile.i: python/profile.cpp.i
.PHONY : python/profile.i

# target to preprocess a source file
python/profile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep_profile.dir/build.make CMakeFiles/tasep_profile.dir/python/profile.cpp.i
.PHONY : python/profile.cpp.i

python/profile.s: python/profile.cpp.s
.PHONY : python/profile.s

# target to generate assembly for a file
python/profile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep_profile.dir/build.make CMakeFiles/tasep_profile.dir/python/profile.cpp.s
.PHONY : python/profile.cpp.s

src/Bindings.o: src/Bindings.cpp.o
.PHONY : src/Bindings.o

# target to build an object file
src/Bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/Bindings.cpp.o
.PHONY : src/Bindings.cpp.o

src/Bindings.i: src/Bindings.cpp.i
.PHONY : src/Bindings.i

# target to preprocess a source file
src/Bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/Bindings.cpp.i
.PHONY : src/Bindings.cpp.i

src/Bindings.s: src/Bindings.cpp.s
.PHONY : src/Bindings.s

# target to generate assembly for a file
src/Bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/Bindings.cpp.s
.PHONY : src/Bindings.cpp.s

src/abstract.o: src/abstract.cpp.o
.PHONY : src/abstract.o

# target to build an object file
src/abstract.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/abstract.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighbors.dir/build.make CMakeFiles/neighbors.dir/src/abstract.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep_profile.dir/build.make CMakeFiles/tasep_profile.dir/src/abstract.cpp.o
.PHONY : src/abstract.cpp.o

src/abstract.i: src/abstract.cpp.i
.PHONY : src/abstract.i

# target to preprocess a source file
src/abstract.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/abstract.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighbors.dir/build.make CMakeFiles/neighbors.dir/src/abstract.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep_profile.dir/build.make CMakeFiles/tasep_profile.dir/src/abstract.cpp.i
.PHONY : src/abstract.cpp.i

src/abstract.s: src/abstract.cpp.s
.PHONY : src/abstract.s

# target to generate assembly for a file
src/abstract.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/abstract.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighbors.dir/build.make CMakeFiles/neighbors.dir/src/abstract.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep_profile.dir/build.make CMakeFiles/tasep_profile.dir/src/abstract.cpp.s
.PHONY : src/abstract.cpp.s

src/full.o: src/full.cpp.o
.PHONY : src/full.o

# target to build an object file
src/full.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/full.cpp.o
.PHONY : src/full.cpp.o

src/full.i: src/full.cpp.i
.PHONY : src/full.i

# target to preprocess a source file
src/full.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/full.cpp.i
.PHONY : src/full.cpp.i

src/full.s: src/full.cpp.s
.PHONY : src/full.s

# target to generate assembly for a file
src/full.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/full.cpp.s
.PHONY : src/full.cpp.s

src/kins_only.o: src/kins_only.cpp.o
.PHONY : src/kins_only.o

# target to build an object file
src/kins_only.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/kins_only.cpp.o
.PHONY : src/kins_only.cpp.o

src/kins_only.i: src/kins_only.cpp.i
.PHONY : src/kins_only.i

# target to preprocess a source file
src/kins_only.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/kins_only.cpp.i
.PHONY : src/kins_only.cpp.i

src/kins_only.s: src/kins_only.cpp.s
.PHONY : src/kins_only.s

# target to generate assembly for a file
src/kins_only.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/kins_only.cpp.s
.PHONY : src/kins_only.cpp.s

src/neighbors.o: src/neighbors.cpp.o
.PHONY : src/neighbors.o

# target to build an object file
src/neighbors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/neighbors.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighbors.dir/build.make CMakeFiles/neighbors.dir/src/neighbors.cpp.o
.PHONY : src/neighbors.cpp.o

src/neighbors.i: src/neighbors.cpp.i
.PHONY : src/neighbors.i

# target to preprocess a source file
src/neighbors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/neighbors.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighbors.dir/build.make CMakeFiles/neighbors.dir/src/neighbors.cpp.i
.PHONY : src/neighbors.cpp.i

src/neighbors.s: src/neighbors.cpp.s
.PHONY : src/neighbors.s

# target to generate assembly for a file
src/neighbors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/neighbors.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighbors.dir/build.make CMakeFiles/neighbors.dir/src/neighbors.cpp.s
.PHONY : src/neighbors.cpp.s

src/phase.o: src/phase.cpp.o
.PHONY : src/phase.o

# target to build an object file
src/phase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/phase.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep_profile.dir/build.make CMakeFiles/tasep_profile.dir/src/phase.cpp.o
.PHONY : src/phase.cpp.o

src/phase.i: src/phase.cpp.i
.PHONY : src/phase.i

# target to preprocess a source file
src/phase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/phase.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep_profile.dir/build.make CMakeFiles/tasep_profile.dir/src/phase.cpp.i
.PHONY : src/phase.cpp.i

src/phase.s: src/phase.cpp.s
.PHONY : src/phase.s

# target to generate assembly for a file
src/phase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep.dir/build.make CMakeFiles/tasep.dir/src/phase.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tasep_profile.dir/build.make CMakeFiles/tasep_profile.dir/src/phase.cpp.s
.PHONY : src/phase.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... neighbors"
	@echo "... tasep"
	@echo "... tasep_profile"
	@echo "... python/neighbors.o"
	@echo "... python/neighbors.i"
	@echo "... python/neighbors.s"
	@echo "... python/profile.o"
	@echo "... python/profile.i"
	@echo "... python/profile.s"
	@echo "... src/Bindings.o"
	@echo "... src/Bindings.i"
	@echo "... src/Bindings.s"
	@echo "... src/abstract.o"
	@echo "... src/abstract.i"
	@echo "... src/abstract.s"
	@echo "... src/full.o"
	@echo "... src/full.i"
	@echo "... src/full.s"
	@echo "... src/kins_only.o"
	@echo "... src/kins_only.i"
	@echo "... src/kins_only.s"
	@echo "... src/neighbors.o"
	@echo "... src/neighbors.i"
	@echo "... src/neighbors.s"
	@echo "... src/phase.o"
	@echo "... src/phase.i"
	@echo "... src/phase.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

