[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "scikit-build",
  "cmake>=3.15",
  "ninja",     # optional but often speeds up builds
  "pybind11>=2.5"
]
build-backend = "setuptools.build_meta"
