from joblib import Parallel, delayed
import sys
import cooperative_tasep_lib as tasep
import numpy as np


"""
secure_sim Function

Runs a simulation with specified parameters and returns the simulation data.

Parameters
----------
L : int Number of sides.
T : int Total time for the simulation.
kon : float  Rate constant for the binding events (on-rate).
koff : float  Rate constant for the unbinding events (off-rate).
kstep : float  Rate of stepping.
kq : float  Rate of deactivation
q : float  Multiplicative factor

Returns
-------
data : numpy.ndarray of shape (10xT+1, L) A binary matrix. The  
    
Notes
-----
- The function flushes the standard output before returning the data to ensure that all outputs are written.
- The simulation is run using the `tasep.sim` function from the `tasep` module.
"""

def secure_sim(L, T, kon, koff, kstep, kq, q):
    data, times = tasep.sim(L, T, kon, koff, kstep, kq, q)
    sys.stdout.flush()
    return data, times

"""
secure_ssim Function

Runs a steady-state simulation with specified parameters and returns the simulation data along with activation information.

Parameters
----------
L : int
    Length of the system.
T : int
    Total time for the simulation.
kon : float
    Rate constant for the association (on-rate).
koff : float
    Rate constant for the dissociation (off-rate).
kstep : float
    Time step for the simulation.
kq : float
    Rate constant related to the queue (specific to the model being used).
q : float
    A parameter affecting the simulation (specific to the model being used).

Returns
-------
data : numpy.ndarray
    The steady-state simulation data generated by the `tasep.ssim` function.
activation : numpy.ndarray
    Activation values generated by the `tasep.ssim` function.

Notes
-----
- The function flushes the standard output before returning the data to ensure that all outputs are written.
- The steady-state simulation is run using the `tasep.ssim` function from the `tasep` module.
"""

def secure_ssim(L, T, kon, koff, kstep, kq, q):
    data, activation, nn, times, res, dts = tasep.ssim(L, T, kon, koff, kstep, kq, q)
    sys.stdout.flush()
    return data, activation


class MultipleExecutionSimple:    
    @staticmethod
    def same_conf_parallel(L, T, kon, koff, kstep, kq, q, num=100):
        results = Parallel(n_jobs=10, prefer="threads")(
            delayed(secure_sim)(L, T, kon, koff, kstep, kq, q)
            for _ in range(num)
        )
        
        return np.stack(results, axis=-1)
    
    def same_conf_serial(L, T, kon, koff, kstep, kq, q, num=100):
        RES = np.zeros((10*T+1, L , num))
        for _ in range(num):
            data = secure_sim(L, T, kon, koff, kstep, kq, q)
            sys.stdout.flush()
            RES[:, :, _] = data

        return RES

    
    @staticmethod
    def sweep_over():
        pass

class MultipleExecutionDetailed:    
    @staticmethod
    def same_conf_parallel(L, T, kon, koff, kstep, kq, q, num=100):
        results = Parallel(n_jobs=10, prefer="threads")(
            delayed(secure_ssim)(L, T, kon, koff, kstep, kq, q)
            for _ in range(num)
        )
        data = [res[0] for res in results]
        activation = [res[1] for res in results]
        return (np.stack(data, axis=-1), np.stack(activation, axis=-1))
        # return np.stack(results, axis=-1)

    
    def same_conf_serial(L, T, kon, koff, kstep, kq, q, num=100):
        RES = np.zeros((10*T+1, L , num))
        for _ in range(num):
            data = secure_ssim(L, T, kon, koff, kstep, kq, q)
            sys.stdout.flush()
            RES[:, :, _] = data

        return RES

    
    @staticmethod
    def sweep_over():
        pass